// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmhlxhatogrrrvuruayv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtaGx4aGF0b2dycnJ2dXJ1YXl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTQwODMsImV4cCI6MjA2ODE3MDA4M30.uBMegZGwmf8CfVqdzrT3gTSV4kcJCoQxDDra-Qd4-b0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});