import React, { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Separator } from '@/components/ui/separator';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { Plus, Edit, Trash2, Wand2, Check, X } from 'lucide-react';
import { StatusBadge } from '@/components/milestones/StatusBadge';

interface Criteria {
  id: string;
  criteria_number: string;
  statement: string;
  summary: string | null;
  ai_suggested_statement: string | null;
  ai_suggested_summary: string | null;
  mps_id: string;
  status: string;
  statement_approved_at: string | null;
  statement_approved_by: string | null;
  created_at: string;
  updated_at: string;
  mps?: {
    name: string;
    mps_number: number;
    domain?: {
      name: string;
    };
  };
  maturity_levels?: MaturityLevel[];
}

interface MaturityLevel {
  id: string;
  level: string;
  descriptor: string;
  ai_suggested_descriptor: string | null;
  descriptor_approved_at: string | null;
  descriptor_approved_by: string | null;
}

interface MPS {
  id: string;
  name: string;
  mps_number: number;
  domain?: {
    name: string;
  };
}

const maturityLevels = ['basic', 'reactive', 'compliant', 'proactive', 'resilient'];

export const CriteriaManagement: React.FC = () => {
  const [criteriaList, setCriteriaList] = useState<Criteria[]>([]);
  const [mpsList, setMpsList] = useState<MPS[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [editingCriteria, setEditingCriteria] = useState<Criteria | null>(null);
  const [formData, setFormData] = useState({
    statement: '',
    summary: '',
    mps_id: ''
  });
  const { toast } = useToast();

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      // Fetch MPS list
      const { data: mpsData, error: mpsError } = await supabase
        .from('maturity_practice_statements')
        .select(`
          id, name, mps_number,
          domain:domains(name)
        `)
        .order('mps_number');

      if (mpsError) throw mpsError;
      setMpsList(mpsData || []);

      // Fetch criteria with MPS and maturity levels
      const { data: criteriaData, error: criteriaError } = await supabase
        .from('criteria')
        .select(`
          *,
          mps:maturity_practice_statements(
            name, mps_number,
            domain:domains(name)
          ),
          maturity_levels(*)
        `)
        .order('criteria_number');

      if (criteriaError) throw criteriaError;
      setCriteriaList(criteriaData || []);
    } catch (error) {
      console.error('Error fetching data:', error);
      toast({
        title: 'Error',
        description: 'Failed to fetch data',
        variant: 'destructive'
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    try {
      const { data: user } = await supabase.auth.getUser();
      if (!user.user) throw new Error('User not authenticated');

      const { data: orgData } = await supabase
        .from('organization_members')
        .select('organization_id')
        .eq('user_id', user.user.id)
        .single();

      if (!orgData) throw new Error('Organization not found');

      if (editingCriteria) {
        // Update existing criteria
        const { error } = await supabase
          .from('criteria')
          .update({
            ...formData,
            updated_by: user.user.id,
            updated_at: new Date().toISOString()
          })
          .eq('id', editingCriteria.id);

        if (error) throw error;
        toast({ title: 'Success', description: 'Criteria updated successfully' });
      } else {
        // Create new criteria - the criteria_number will be auto-generated by the trigger
        const { data: newCriteria, error } = await supabase
          .from('criteria')
          .insert({
            statement: formData.statement,
            summary: formData.summary || null,
            mps_id: formData.mps_id,
            criteria_number: '0.0', // Temporary, will be auto-generated by trigger
            organization_id: orgData.organization_id,
            created_by: user.user.id,
            updated_by: user.user.id,
            status: 'not_started'
          })
          .select()
          .single();

        if (error) throw error;

        // Create default maturity levels for the new criteria
        const maturityLevelInserts = maturityLevels.map(level => ({
          criteria_id: newCriteria.id,
          organization_id: orgData.organization_id,
          level: level as 'basic' | 'reactive' | 'compliant' | 'proactive' | 'resilient',
          descriptor: `${level.charAt(0).toUpperCase() + level.slice(1)} level descriptor for ${formData.statement}`,
          created_by: user.user.id,
          updated_by: user.user.id
        }));

        const { error: mlError } = await supabase
          .from('maturity_levels')
          .insert(maturityLevelInserts);

        if (mlError) throw mlError;

        toast({ title: 'Success', description: 'Criteria created successfully with maturity levels' });
      }

      setIsDialogOpen(false);
      setEditingCriteria(null);
      setFormData({ statement: '', summary: '', mps_id: '' });
      fetchData();
    } catch (error) {
      console.error('Error saving criteria:', error);
      toast({
        title: 'Error',
        description: 'Failed to save criteria',
        variant: 'destructive'
      });
    }
  };

  const handleDelete = async (criteriaId: string) => {
    if (!confirm('Are you sure you want to delete this criteria? This will also delete all associated maturity levels.')) return;

    try {
      const { error } = await supabase
        .from('criteria')
        .delete()
        .eq('id', criteriaId);

      if (error) throw error;
      toast({ title: 'Success', description: 'Criteria deleted successfully' });
      fetchData();
    } catch (error) {
      console.error('Error deleting criteria:', error);
      toast({
        title: 'Error',
        description: 'Failed to delete criteria',
        variant: 'destructive'
      });
    }
  };

  const generateAIDescriptors = async (criteriaId: string, statement: string) => {
    try {
      const { data: user } = await supabase.auth.getUser();
      if (!user.user) throw new Error('User not authenticated');

      // Generate AI descriptors for each maturity level
      const descriptorUpdates = maturityLevels.map(level => {
        const descriptor = `AI-generated ${level} level descriptor for: ${statement}. This level demonstrates ${level} capabilities in implementation and governance.`;
        return {
          level,
          descriptor
        };
      });

      // Update maturity levels with AI suggestions
      for (const update of descriptorUpdates) {
        const { error } = await supabase
          .from('maturity_levels')
          .update({
            ai_suggested_descriptor: update.descriptor,
            updated_by: user.user.id,
            updated_at: new Date().toISOString()
          })
          .eq('criteria_id', criteriaId)
          .eq('level', update.level as 'basic' | 'reactive' | 'compliant' | 'proactive' | 'resilient');

        if (error) throw error;
      }

      toast({ title: 'Success', description: 'AI descriptors generated for all maturity levels' });
      fetchData();
    } catch (error) {
      console.error('Error generating AI descriptors:', error);
      toast({
        title: 'Error',
        description: 'Failed to generate AI descriptors',
        variant: 'destructive'
      });
    }
  };

  const approveCriteria = async (criteriaId: string) => {
    try {
      const { data: user } = await supabase.auth.getUser();
      if (!user.user) throw new Error('User not authenticated');

      const { error } = await supabase
        .from('criteria')
        .update({
          statement_approved_at: new Date().toISOString(),
          statement_approved_by: user.user.id,
          status: 'approved_locked',
          updated_by: user.user.id,
          updated_at: new Date().toISOString()
        })
        .eq('id', criteriaId);

      if (error) throw error;
      toast({ title: 'Success', description: 'Criteria statement approved' });
      fetchData();
    } catch (error) {
      console.error('Error approving criteria:', error);
      toast({
        title: 'Error',
        description: 'Failed to approve criteria statement',
        variant: 'destructive'
      });
    }
  };

  const openEditDialog = (criteria: Criteria) => {
    setEditingCriteria(criteria);
    setFormData({
      statement: criteria.statement,
      summary: criteria.summary || '',
      mps_id: criteria.mps_id
    });
    setIsDialogOpen(true);
  };

  const openCreateDialog = () => {
    setEditingCriteria(null);
    setFormData({ statement: '', summary: '', mps_id: '' });
    setIsDialogOpen(true);
  };

  if (isLoading) {
    return <div className="flex justify-center p-8">Loading criteria...</div>;
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h3 className="text-lg font-semibold">Assessment Criteria</h3>
          <p className="text-sm text-muted-foreground">
            Define criteria with auto-numbering and AI-generated maturity descriptors
          </p>
        </div>
        <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
          <DialogTrigger asChild>
            <Button onClick={openCreateDialog}>
              <Plus className="h-4 w-4 mr-2" />
              Add Criteria
            </Button>
          </DialogTrigger>
          <DialogContent className="sm:max-w-[700px]">
            <DialogHeader>
              <DialogTitle>
                {editingCriteria ? 'Edit Criteria' : 'Create New Criteria'}
              </DialogTitle>
            </DialogHeader>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="mps_id">Maturity Practice Statement</Label>
                <Select
                  value={formData.mps_id}
                  onValueChange={(value) => setFormData(prev => ({ ...prev, mps_id: value }))}
                  required
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select MPS" />
                  </SelectTrigger>
                  <SelectContent>
                    {mpsList.map((mps) => (
                      <SelectItem key={mps.id} value={mps.id}>
                        MPS {mps.mps_number}: {mps.name} ({mps.domain?.name})
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="statement">Criteria Statement</Label>
                <Textarea
                  id="statement"
                  value={formData.statement}
                  onChange={(e) => setFormData(prev => ({ ...prev, statement: e.target.value }))}
                  placeholder="Define the criteria statement"
                  rows={4}
                  required
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="summary">Summary (Optional)</Label>
                <Textarea
                  id="summary"
                  value={formData.summary}
                  onChange={(e) => setFormData(prev => ({ ...prev, summary: e.target.value }))}
                  placeholder="Brief summary of the criteria"
                  rows={3}
                />
              </div>
              <div className="flex justify-end space-x-2">
                <Button type="button" variant="outline" onClick={() => setIsDialogOpen(false)}>
                  Cancel
                </Button>
                <Button type="submit">
                  {editingCriteria ? 'Update' : 'Create'} Criteria
                </Button>
              </div>
            </form>
          </DialogContent>
        </Dialog>
      </div>

      <div className="grid gap-6">
        {criteriaList.length === 0 ? (
          <Card>
            <CardContent className="flex flex-col items-center justify-center py-8">
              <p className="text-muted-foreground mb-4">No criteria configured yet</p>
              <Button onClick={openCreateDialog}>
                <Plus className="h-4 w-4 mr-2" />
                Create First Criteria
              </Button>
            </CardContent>
          </Card>
        ) : (
          criteriaList.map((criteria) => (
            <Card key={criteria.id}>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-3">
                    <Badge variant="outline">{criteria.criteria_number}</Badge>
                    <CardTitle className="text-lg">Assessment Criteria</CardTitle>
                    <StatusBadge status={criteria.status} />
                  </div>
                  <div className="flex items-center space-x-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => openEditDialog(criteria)}
                    >
                      <Edit className="h-4 w-4" />
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleDelete(criteria.id)}
                    >
                      <Trash2 className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
                <div className="flex items-center text-sm text-muted-foreground">
                  <span>MPS {criteria.mps?.mps_number}: {criteria.mps?.name} | Domain: {criteria.mps?.domain?.name}</span>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <Label className="text-sm font-medium">Criteria Statement</Label>
                  <p className="text-sm text-muted-foreground mt-1">{criteria.statement}</p>
                  {criteria.statement_approved_at ? (
                    <Badge variant="default" className="mt-2">
                      <Check className="h-3 w-3 mr-1" />
                      Approved
                    </Badge>
                  ) : (
                    <Button
                      size="sm"
                      variant="outline"
                      className="mt-2"
                      onClick={() => approveCriteria(criteria.id)}
                    >
                      <Check className="h-4 w-4 mr-1" />
                      Approve Statement
                    </Button>
                  )}
                </div>

                {criteria.summary && (
                  <div>
                    <Label className="text-sm font-medium">Summary</Label>
                    <p className="text-sm text-muted-foreground mt-1">{criteria.summary}</p>
                  </div>
                )}

                <Separator />

                <div>
                  <div className="flex items-center justify-between mb-3">
                    <Label className="text-sm font-medium">Maturity Levels</Label>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => generateAIDescriptors(criteria.id, criteria.statement)}
                    >
                      <Wand2 className="h-4 w-4 mr-1" />
                      Generate AI Descriptors
                    </Button>
                  </div>
                  
                  <div className="grid gap-3">
                    {criteria.maturity_levels?.map((level) => (
                      <div key={level.id} className="border rounded-lg p-3">
                        <div className="flex items-center justify-between mb-2">
                          <Badge variant="secondary" className="capitalize">
                            {level.level}
                          </Badge>
                          {level.descriptor_approved_at && (
                            <Badge variant="default">
                              <Check className="h-3 w-3 mr-1" />
                              Approved
                            </Badge>
                          )}
                        </div>
                        <p className="text-sm text-muted-foreground">{level.descriptor}</p>
                        
                        {level.ai_suggested_descriptor && (
                          <div className="mt-2 p-2 bg-muted rounded border-l-4 border-primary">
                            <Label className="text-xs font-medium flex items-center">
                              <Wand2 className="h-3 w-3 mr-1" />
                              AI Suggestion
                            </Label>
                            <p className="text-xs text-muted-foreground mt-1">{level.ai_suggested_descriptor}</p>
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>
    </div>
  );
};